/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ForBrandsRouteImport } from './routes/for-brands'
import { Route as HomeRouteImport } from './routes/home'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as TrustRouteImport } from './routes/trust'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as ApiLandingChatRouteImport } from './routes/api/landing-chat'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardAdminRouteImport } from './routes/dashboard.admin'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard.analytics'
import { Route as DashboardApprovalsRouteImport } from './routes/dashboard.approvals'
import { Route as DashboardBrandsRouteImport } from './routes/dashboard.brands'
import { Route as DashboardCampaignsRouteImport } from './routes/dashboard.campaigns'
import { Route as DashboardDealsRouteImport } from './routes/dashboard.deals'
import { Route as DashboardInboxRouteImport } from './routes/dashboard.inbox'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardToolsRouteImport } from './routes/dashboard.tools'
import { Route as DashboardTrackerRouteImport } from './routes/dashboard.tracker'
import { Route as DashboardWalletRouteImport } from './routes/dashboard.wallet'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as OnboardingStep1RouteImport } from './routes/onboarding.step-1'
import { Route as OnboardingStep2RouteImport } from './routes/onboarding.step-2'
import { Route as OnboardingStep3RouteImport } from './routes/onboarding.step-3'
import { Route as PayIdRouteImport } from './routes/pay.$id'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as ApiChatAgentRouteImport } from './routes/api.chat.agent'
import { Route as ApiChatLandingRouteImport } from './routes/api.chat.landing'
import { Route as ApiChatOnboardingRouteImport } from './routes/api.chat.onboarding'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api.public.stripe-webhook'
import { Route as DashboardAdminIndexRouteImport } from './routes/dashboard.admin.index'
import { Route as DashboardDealsIdRouteImport } from './routes/dashboard.deals.$id'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as ApiPublicHooksAutoReleaseEscrowRouteImport } from './routes/api.public.hooks.auto-release-escrow'
import { Route as ApiPublicHooksDailyDigestRouteImport } from './routes/api.public.hooks.daily-digest'
import { Route as ApiPublicHooksHealthRouteImport } from './routes/api.public.hooks.health'
import { Route as ApiPublicHooksPollRepliesRouteImport } from './routes/api.public.hooks.poll-replies'
import { Route as ApiPublicHooksProcessFollowUpsRouteImport } from './routes/api.public.hooks.process-follow-ups'
import { Route as ApiPublicHooksResendInboundRouteImport } from './routes/api.public.hooks.resend-inbound'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as ApiPublicEmailClickTidRouteImport } from './routes/api.public.email.click.$tid'
import { Route as ApiPublicEmailOpenTidRouteImport } from './routes/api.public.email.open.$tid'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ForBrandsRoute = ForBrandsRouteImport.update({
  id: '/for-brands',
  path: '/for-brands',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TrustRoute = TrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiLandingChatRoute = ApiLandingChatRouteImport.update({
  id: '/api/landing-chat',
  path: '/api/landing-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardApprovalsRoute = DashboardApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBrandsRoute = DashboardBrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCampaignsRoute = DashboardCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDealsRoute = DashboardDealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInboxRoute = DashboardInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardToolsRoute = DashboardToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTrackerRoute = DashboardTrackerRouteImport.update({
  id: '/tracker',
  path: '/tracker',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardWalletRoute = DashboardWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => DashboardRoute,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingStep1Route = OnboardingStep1RouteImport.update({
  id: '/step-1',
  path: '/step-1',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingStep2Route = OnboardingStep2RouteImport.update({
  id: '/step-2',
  path: '/step-2',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingStep3Route = OnboardingStep3RouteImport.update({
  id: '/step-3',
  path: '/step-3',
  getParentRoute: () => OnboardingRoute,
} as any)
const PayIdRoute = PayIdRouteImport.update({
  id: '/pay/$id',
  path: '/pay/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiChatAgentRoute = ApiChatAgentRouteImport.update({
  id: '/api/chat/agent',
  path: '/api/chat/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatLandingRoute = ApiChatLandingRouteImport.update({
  id: '/api/chat/landing',
  path: '/api/chat/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatOnboardingRoute = ApiChatOnboardingRouteImport.update({
  id: '/api/chat/onboarding',
  path: '/api/chat/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe-webhook',
  path: '/api/public/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminIndexRoute = DashboardAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardDealsIdRoute = DashboardDealsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DashboardDealsRoute,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksAutoReleaseEscrowRoute =
  ApiPublicHooksAutoReleaseEscrowRouteImport.update({
    id: '/api/public/hooks/auto-release-escrow',
    path: '/api/public/hooks/auto-release-escrow',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDailyDigestRoute =
  ApiPublicHooksDailyDigestRouteImport.update({
    id: '/api/public/hooks/daily-digest',
    path: '/api/public/hooks/daily-digest',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksHealthRoute = ApiPublicHooksHealthRouteImport.update({
  id: '/api/public/hooks/health',
  path: '/api/public/hooks/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksPollRepliesRoute =
  ApiPublicHooksPollRepliesRouteImport.update({
    id: '/api/public/hooks/poll-replies',
    path: '/api/public/hooks/poll-replies',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksProcessFollowUpsRoute =
  ApiPublicHooksProcessFollowUpsRouteImport.update({
    id: '/api/public/hooks/process-follow-ups',
    path: '/api/public/hooks/process-follow-ups',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksResendInboundRoute =
  ApiPublicHooksResendInboundRouteImport.update({
    id: '/api/public/hooks/resend-inbound',
    path: '/api/public/hooks/resend-inbound',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicEmailClickTidRoute = ApiPublicEmailClickTidRouteImport.update({
  id: '/api/public/email/click/$tid',
  path: '/api/public/email/click/$tid',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEmailOpenTidRoute = ApiPublicEmailOpenTidRouteImport.update({
  id: '/api/public/email/open/$tid',
  path: '/api/public/email/open/$tid',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/for-brands': typeof ForBrandsRoute
  '/home': typeof HomeRoute
  '/mcp': typeof McpRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/trust': typeof TrustRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/landing-chat': typeof ApiLandingChatRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/dashboard/admin': typeof DashboardAdminRouteWithChildren
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/approvals': typeof DashboardApprovalsRoute
  '/dashboard/brands': typeof DashboardBrandsRoute
  '/dashboard/campaigns': typeof DashboardCampaignsRoute
  '/dashboard/deals': typeof DashboardDealsRouteWithChildren
  '/dashboard/inbox': typeof DashboardInboxRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/tools': typeof DashboardToolsRoute
  '/dashboard/tracker': typeof DashboardTrackerRoute
  '/dashboard/wallet': typeof DashboardWalletRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/onboarding/step-1': typeof OnboardingStep1Route
  '/onboarding/step-2': typeof OnboardingStep2Route
  '/onboarding/step-3': typeof OnboardingStep3Route
  '/pay/$id': typeof PayIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/chat/agent': typeof ApiChatAgentRoute
  '/api/chat/landing': typeof ApiChatLandingRoute
  '/api/chat/onboarding': typeof ApiChatOnboardingRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/dashboard/deals/$id': typeof DashboardDealsIdRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/api/public/hooks/auto-release-escrow': typeof ApiPublicHooksAutoReleaseEscrowRoute
  '/api/public/hooks/daily-digest': typeof ApiPublicHooksDailyDigestRoute
  '/api/public/hooks/health': typeof ApiPublicHooksHealthRoute
  '/api/public/hooks/poll-replies': typeof ApiPublicHooksPollRepliesRoute
  '/api/public/hooks/process-follow-ups': typeof ApiPublicHooksProcessFollowUpsRoute
  '/api/public/hooks/resend-inbound': typeof ApiPublicHooksResendInboundRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/api/public/email/click/$tid': typeof ApiPublicEmailClickTidRoute
  '/api/public/email/open/$tid': typeof ApiPublicEmailOpenTidRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/for-brands': typeof ForBrandsRoute
  '/home': typeof HomeRoute
  '/mcp': typeof McpRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/trust': typeof TrustRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/landing-chat': typeof ApiLandingChatRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/approvals': typeof DashboardApprovalsRoute
  '/dashboard/brands': typeof DashboardBrandsRoute
  '/dashboard/campaigns': typeof DashboardCampaignsRoute
  '/dashboard/deals': typeof DashboardDealsRouteWithChildren
  '/dashboard/inbox': typeof DashboardInboxRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/tools': typeof DashboardToolsRoute
  '/dashboard/tracker': typeof DashboardTrackerRoute
  '/dashboard/wallet': typeof DashboardWalletRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/onboarding/step-1': typeof OnboardingStep1Route
  '/onboarding/step-2': typeof OnboardingStep2Route
  '/onboarding/step-3': typeof OnboardingStep3Route
  '/pay/$id': typeof PayIdRoute
  '/dashboard': typeof DashboardIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/chat/agent': typeof ApiChatAgentRoute
  '/api/chat/landing': typeof ApiChatLandingRoute
  '/api/chat/onboarding': typeof ApiChatOnboardingRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/dashboard/deals/$id': typeof DashboardDealsIdRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/dashboard/admin': typeof DashboardAdminIndexRoute
  '/api/public/hooks/auto-release-escrow': typeof ApiPublicHooksAutoReleaseEscrowRoute
  '/api/public/hooks/daily-digest': typeof ApiPublicHooksDailyDigestRoute
  '/api/public/hooks/health': typeof ApiPublicHooksHealthRoute
  '/api/public/hooks/poll-replies': typeof ApiPublicHooksPollRepliesRoute
  '/api/public/hooks/process-follow-ups': typeof ApiPublicHooksProcessFollowUpsRoute
  '/api/public/hooks/resend-inbound': typeof ApiPublicHooksResendInboundRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/api/public/email/click/$tid': typeof ApiPublicEmailClickTidRoute
  '/api/public/email/open/$tid': typeof ApiPublicEmailOpenTidRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/for-brands': typeof ForBrandsRoute
  '/home': typeof HomeRoute
  '/mcp': typeof McpRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/trust': typeof TrustRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/landing-chat': typeof ApiLandingChatRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/dashboard/admin': typeof DashboardAdminRouteWithChildren
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/approvals': typeof DashboardApprovalsRoute
  '/dashboard/brands': typeof DashboardBrandsRoute
  '/dashboard/campaigns': typeof DashboardCampaignsRoute
  '/dashboard/deals': typeof DashboardDealsRouteWithChildren
  '/dashboard/inbox': typeof DashboardInboxRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/tools': typeof DashboardToolsRoute
  '/dashboard/tracker': typeof DashboardTrackerRoute
  '/dashboard/wallet': typeof DashboardWalletRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/onboarding/step-1': typeof OnboardingStep1Route
  '/onboarding/step-2': typeof OnboardingStep2Route
  '/onboarding/step-3': typeof OnboardingStep3Route
  '/pay/$id': typeof PayIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/chat/agent': typeof ApiChatAgentRoute
  '/api/chat/landing': typeof ApiChatLandingRoute
  '/api/chat/onboarding': typeof ApiChatOnboardingRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/dashboard/deals/$id': typeof DashboardDealsIdRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/api/public/hooks/auto-release-escrow': typeof ApiPublicHooksAutoReleaseEscrowRoute
  '/api/public/hooks/daily-digest': typeof ApiPublicHooksDailyDigestRoute
  '/api/public/hooks/health': typeof ApiPublicHooksHealthRoute
  '/api/public/hooks/poll-replies': typeof ApiPublicHooksPollRepliesRoute
  '/api/public/hooks/process-follow-ups': typeof ApiPublicHooksProcessFollowUpsRoute
  '/api/public/hooks/resend-inbound': typeof ApiPublicHooksResendInboundRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/api/public/email/click/$tid': typeof ApiPublicEmailClickTidRoute
  '/api/public/email/open/$tid': typeof ApiPublicEmailOpenTidRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/for-brands'
    | '/home'
    | '/mcp'
    | '/onboarding'
    | '/reset-password'
    | '/trust'
    | '/unsubscribe'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/api/landing-chat'
    | '/checkout/return'
    | '/dashboard/admin'
    | '/dashboard/analytics'
    | '/dashboard/approvals'
    | '/dashboard/brands'
    | '/dashboard/campaigns'
    | '/dashboard/deals'
    | '/dashboard/inbox'
    | '/dashboard/settings'
    | '/dashboard/tools'
    | '/dashboard/tracker'
    | '/dashboard/wallet'
    | '/email/unsubscribe'
    | '/onboarding/step-1'
    | '/onboarding/step-2'
    | '/onboarding/step-3'
    | '/pay/$id'
    | '/dashboard/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/chat/agent'
    | '/api/chat/landing'
    | '/api/chat/onboarding'
    | '/api/public/stripe-webhook'
    | '/dashboard/deals/$id'
    | '/lovable/email/suppression'
    | '/dashboard/admin/'
    | '/api/public/hooks/auto-release-escrow'
    | '/api/public/hooks/daily-digest'
    | '/api/public/hooks/health'
    | '/api/public/hooks/poll-replies'
    | '/api/public/hooks/process-follow-ups'
    | '/api/public/hooks/resend-inbound'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/api/public/email/click/$tid'
    | '/api/public/email/open/$tid'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/for-brands'
    | '/home'
    | '/mcp'
    | '/onboarding'
    | '/reset-password'
    | '/trust'
    | '/unsubscribe'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/api/landing-chat'
    | '/checkout/return'
    | '/dashboard/analytics'
    | '/dashboard/approvals'
    | '/dashboard/brands'
    | '/dashboard/campaigns'
    | '/dashboard/deals'
    | '/dashboard/inbox'
    | '/dashboard/settings'
    | '/dashboard/tools'
    | '/dashboard/tracker'
    | '/dashboard/wallet'
    | '/email/unsubscribe'
    | '/onboarding/step-1'
    | '/onboarding/step-2'
    | '/onboarding/step-3'
    | '/pay/$id'
    | '/dashboard'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/chat/agent'
    | '/api/chat/landing'
    | '/api/chat/onboarding'
    | '/api/public/stripe-webhook'
    | '/dashboard/deals/$id'
    | '/lovable/email/suppression'
    | '/dashboard/admin'
    | '/api/public/hooks/auto-release-escrow'
    | '/api/public/hooks/daily-digest'
    | '/api/public/hooks/health'
    | '/api/public/hooks/poll-replies'
    | '/api/public/hooks/process-follow-ups'
    | '/api/public/hooks/resend-inbound'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/api/public/email/click/$tid'
    | '/api/public/email/open/$tid'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/for-brands'
    | '/home'
    | '/mcp'
    | '/onboarding'
    | '/reset-password'
    | '/trust'
    | '/unsubscribe'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/api/landing-chat'
    | '/checkout/return'
    | '/dashboard/admin'
    | '/dashboard/analytics'
    | '/dashboard/approvals'
    | '/dashboard/brands'
    | '/dashboard/campaigns'
    | '/dashboard/deals'
    | '/dashboard/inbox'
    | '/dashboard/settings'
    | '/dashboard/tools'
    | '/dashboard/tracker'
    | '/dashboard/wallet'
    | '/email/unsubscribe'
    | '/onboarding/step-1'
    | '/onboarding/step-2'
    | '/onboarding/step-3'
    | '/pay/$id'
    | '/dashboard/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/chat/agent'
    | '/api/chat/landing'
    | '/api/chat/onboarding'
    | '/api/public/stripe-webhook'
    | '/dashboard/deals/$id'
    | '/lovable/email/suppression'
    | '/dashboard/admin/'
    | '/api/public/hooks/auto-release-escrow'
    | '/api/public/hooks/daily-digest'
    | '/api/public/hooks/health'
    | '/api/public/hooks/poll-replies'
    | '/api/public/hooks/process-follow-ups'
    | '/api/public/hooks/resend-inbound'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/api/public/email/click/$tid'
    | '/api/public/email/open/$tid'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ForBrandsRoute: typeof ForBrandsRoute
  HomeRoute: typeof HomeRoute
  McpRoute: typeof McpRoute
  OnboardingRoute: typeof OnboardingRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  TrustRoute: typeof TrustRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ApiLandingChatRoute: typeof ApiLandingChatRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  PayIdRoute: typeof PayIdRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiChatAgentRoute: typeof ApiChatAgentRoute
  ApiChatLandingRoute: typeof ApiChatLandingRoute
  ApiChatOnboardingRoute: typeof ApiChatOnboardingRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiPublicHooksAutoReleaseEscrowRoute: typeof ApiPublicHooksAutoReleaseEscrowRoute
  ApiPublicHooksDailyDigestRoute: typeof ApiPublicHooksDailyDigestRoute
  ApiPublicHooksHealthRoute: typeof ApiPublicHooksHealthRoute
  ApiPublicHooksPollRepliesRoute: typeof ApiPublicHooksPollRepliesRoute
  ApiPublicHooksProcessFollowUpsRoute: typeof ApiPublicHooksProcessFollowUpsRoute
  ApiPublicHooksResendInboundRoute: typeof ApiPublicHooksResendInboundRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
  ApiPublicEmailClickTidRoute: typeof ApiPublicEmailClickTidRoute
  ApiPublicEmailOpenTidRoute: typeof ApiPublicEmailOpenTidRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-brands': {
      id: '/for-brands'
      path: '/for-brands'
      fullPath: '/for-brands'
      preLoaderRoute: typeof ForBrandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trust': {
      id: '/trust'
      path: '/trust'
      fullPath: '/trust'
      preLoaderRoute: typeof TrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/landing-chat': {
      id: '/api/landing-chat'
      path: '/api/landing-chat'
      fullPath: '/api/landing-chat'
      preLoaderRoute: typeof ApiLandingChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/approvals': {
      id: '/dashboard/approvals'
      path: '/approvals'
      fullPath: '/dashboard/approvals'
      preLoaderRoute: typeof DashboardApprovalsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/brands': {
      id: '/dashboard/brands'
      path: '/brands'
      fullPath: '/dashboard/brands'
      preLoaderRoute: typeof DashboardBrandsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/campaigns': {
      id: '/dashboard/campaigns'
      path: '/campaigns'
      fullPath: '/dashboard/campaigns'
      preLoaderRoute: typeof DashboardCampaignsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/deals': {
      id: '/dashboard/deals'
      path: '/deals'
      fullPath: '/dashboard/deals'
      preLoaderRoute: typeof DashboardDealsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/inbox': {
      id: '/dashboard/inbox'
      path: '/inbox'
      fullPath: '/dashboard/inbox'
      preLoaderRoute: typeof DashboardInboxRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/tools': {
      id: '/dashboard/tools'
      path: '/tools'
      fullPath: '/dashboard/tools'
      preLoaderRoute: typeof DashboardToolsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/tracker': {
      id: '/dashboard/tracker'
      path: '/tracker'
      fullPath: '/dashboard/tracker'
      preLoaderRoute: typeof DashboardTrackerRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/wallet': {
      id: '/dashboard/wallet'
      path: '/wallet'
      fullPath: '/dashboard/wallet'
      preLoaderRoute: typeof DashboardWalletRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/step-1': {
      id: '/onboarding/step-1'
      path: '/step-1'
      fullPath: '/onboarding/step-1'
      preLoaderRoute: typeof OnboardingStep1RouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/step-2': {
      id: '/onboarding/step-2'
      path: '/step-2'
      fullPath: '/onboarding/step-2'
      preLoaderRoute: typeof OnboardingStep2RouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/step-3': {
      id: '/onboarding/step-3'
      path: '/step-3'
      fullPath: '/onboarding/step-3'
      preLoaderRoute: typeof OnboardingStep3RouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/pay/$id': {
      id: '/pay/$id'
      path: '/pay/$id'
      fullPath: '/pay/$id'
      preLoaderRoute: typeof PayIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat/agent': {
      id: '/api/chat/agent'
      path: '/api/chat/agent'
      fullPath: '/api/chat/agent'
      preLoaderRoute: typeof ApiChatAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat/landing': {
      id: '/api/chat/landing'
      path: '/api/chat/landing'
      fullPath: '/api/chat/landing'
      preLoaderRoute: typeof ApiChatLandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat/onboarding': {
      id: '/api/chat/onboarding'
      path: '/api/chat/onboarding'
      fullPath: '/api/chat/onboarding'
      preLoaderRoute: typeof ApiChatOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/stripe-webhook': {
      id: '/api/public/stripe-webhook'
      path: '/api/public/stripe-webhook'
      fullPath: '/api/public/stripe-webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin/': {
      id: '/dashboard/admin/'
      path: '/'
      fullPath: '/dashboard/admin/'
      preLoaderRoute: typeof DashboardAdminIndexRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/deals/$id': {
      id: '/dashboard/deals/$id'
      path: '/$id'
      fullPath: '/dashboard/deals/$id'
      preLoaderRoute: typeof DashboardDealsIdRouteImport
      parentRoute: typeof DashboardDealsRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/auto-release-escrow': {
      id: '/api/public/hooks/auto-release-escrow'
      path: '/api/public/hooks/auto-release-escrow'
      fullPath: '/api/public/hooks/auto-release-escrow'
      preLoaderRoute: typeof ApiPublicHooksAutoReleaseEscrowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/daily-digest': {
      id: '/api/public/hooks/daily-digest'
      path: '/api/public/hooks/daily-digest'
      fullPath: '/api/public/hooks/daily-digest'
      preLoaderRoute: typeof ApiPublicHooksDailyDigestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/health': {
      id: '/api/public/hooks/health'
      path: '/api/public/hooks/health'
      fullPath: '/api/public/hooks/health'
      preLoaderRoute: typeof ApiPublicHooksHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/poll-replies': {
      id: '/api/public/hooks/poll-replies'
      path: '/api/public/hooks/poll-replies'
      fullPath: '/api/public/hooks/poll-replies'
      preLoaderRoute: typeof ApiPublicHooksPollRepliesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/process-follow-ups': {
      id: '/api/public/hooks/process-follow-ups'
      path: '/api/public/hooks/process-follow-ups'
      fullPath: '/api/public/hooks/process-follow-ups'
      preLoaderRoute: typeof ApiPublicHooksProcessFollowUpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/resend-inbound': {
      id: '/api/public/hooks/resend-inbound'
      path: '/api/public/hooks/resend-inbound'
      fullPath: '/api/public/hooks/resend-inbound'
      preLoaderRoute: typeof ApiPublicHooksResendInboundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/email/click/$tid': {
      id: '/api/public/email/click/$tid'
      path: '/api/public/email/click/$tid'
      fullPath: '/api/public/email/click/$tid'
      preLoaderRoute: typeof ApiPublicEmailClickTidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/email/open/$tid': {
      id: '/api/public/email/open/$tid'
      path: '/api/public/email/open/$tid'
      fullPath: '/api/public/email/open/$tid'
      preLoaderRoute: typeof ApiPublicEmailOpenTidRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardAdminRouteChildren {
  DashboardAdminIndexRoute: typeof DashboardAdminIndexRoute
}

const DashboardAdminRouteChildren: DashboardAdminRouteChildren = {
  DashboardAdminIndexRoute: DashboardAdminIndexRoute,
}

const DashboardAdminRouteWithChildren = DashboardAdminRoute._addFileChildren(
  DashboardAdminRouteChildren,
)

interface DashboardDealsRouteChildren {
  DashboardDealsIdRoute: typeof DashboardDealsIdRoute
}

const DashboardDealsRouteChildren: DashboardDealsRouteChildren = {
  DashboardDealsIdRoute: DashboardDealsIdRoute,
}

const DashboardDealsRouteWithChildren = DashboardDealsRoute._addFileChildren(
  DashboardDealsRouteChildren,
)

interface DashboardRouteChildren {
  DashboardAdminRoute: typeof DashboardAdminRouteWithChildren
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardApprovalsRoute: typeof DashboardApprovalsRoute
  DashboardBrandsRoute: typeof DashboardBrandsRoute
  DashboardCampaignsRoute: typeof DashboardCampaignsRoute
  DashboardDealsRoute: typeof DashboardDealsRouteWithChildren
  DashboardInboxRoute: typeof DashboardInboxRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardToolsRoute: typeof DashboardToolsRoute
  DashboardTrackerRoute: typeof DashboardTrackerRoute
  DashboardWalletRoute: typeof DashboardWalletRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAdminRoute: DashboardAdminRouteWithChildren,
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardApprovalsRoute: DashboardApprovalsRoute,
  DashboardBrandsRoute: DashboardBrandsRoute,
  DashboardCampaignsRoute: DashboardCampaignsRoute,
  DashboardDealsRoute: DashboardDealsRouteWithChildren,
  DashboardInboxRoute: DashboardInboxRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardToolsRoute: DashboardToolsRoute,
  DashboardTrackerRoute: DashboardTrackerRoute,
  DashboardWalletRoute: DashboardWalletRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface OnboardingRouteChildren {
  OnboardingStep1Route: typeof OnboardingStep1Route
  OnboardingStep2Route: typeof OnboardingStep2Route
  OnboardingStep3Route: typeof OnboardingStep3Route
}

const OnboardingRouteChildren: OnboardingRouteChildren = {
  OnboardingStep1Route: OnboardingStep1Route,
  OnboardingStep2Route: OnboardingStep2Route,
  OnboardingStep3Route: OnboardingStep3Route,
}

const OnboardingRouteWithChildren = OnboardingRoute._addFileChildren(
  OnboardingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ForBrandsRoute: ForBrandsRoute,
  HomeRoute: HomeRoute,
  McpRoute: McpRoute,
  OnboardingRoute: OnboardingRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  TrustRoute: TrustRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ApiLandingChatRoute: ApiLandingChatRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  PayIdRoute: PayIdRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiChatAgentRoute: ApiChatAgentRoute,
  ApiChatLandingRoute: ApiChatLandingRoute,
  ApiChatOnboardingRoute: ApiChatOnboardingRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPublicHooksAutoReleaseEscrowRoute: ApiPublicHooksAutoReleaseEscrowRoute,
  ApiPublicHooksDailyDigestRoute: ApiPublicHooksDailyDigestRoute,
  ApiPublicHooksHealthRoute: ApiPublicHooksHealthRoute,
  ApiPublicHooksPollRepliesRoute: ApiPublicHooksPollRepliesRoute,
  ApiPublicHooksProcessFollowUpsRoute: ApiPublicHooksProcessFollowUpsRoute,
  ApiPublicHooksResendInboundRoute: ApiPublicHooksResendInboundRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
  ApiPublicEmailClickTidRoute: ApiPublicEmailClickTidRoute,
  ApiPublicEmailOpenTidRoute: ApiPublicEmailOpenTidRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
