// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

function createMissingSupabaseClient(message: string) {
  const error = new Error(message);
  const terminal = Promise.resolve({ data: null, error });

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const chain: any = new Proxy(function noop() {}, {
    get(_target, prop) {
      if (prop === "then") return terminal.then.bind(terminal);
      return chain;
    },
    apply() {
      return chain;
    },
  });

  const auth = {
    getSession: async () => ({ data: { session: null }, error: null }),
    getUser: async () => ({ data: { user: null }, error: null }),
    onAuthStateChange: () => ({
      data: {
        subscription: {
          unsubscribe() {},
        },
      },
    }),
    signInWithPassword: async () => ({ data: { user: null, session: null }, error }),
    signInWithOtp: async () => ({ data: { user: null, session: null }, error }),
    signInWithOAuth: async () => ({ data: null, error }),
    signUp: async () => ({ data: { user: null, session: null }, error }),
    signOut: async () => ({ error: null }),
    resetPasswordForEmail: async () => ({ data: null, error }),
    exchangeCodeForSession: async () => ({ data: { session: null }, error }),
    refreshSession: async () => ({ data: { session: null }, error }),
    updateUser: async () => ({ data: { user: null }, error }),
  };

  return {
    auth,
    from: () => chain,
    rpc: async () => terminal,
    storage: {
      from: () => chain,
    },
    channel: () => ({
      on: () => ({
        subscribe: () => ({ unsubscribe() {} }),
      }),
      subscribe: () => ({ unsubscribe() {} }),
    }),
    removeChannel: async () => {},
    functions: {
      invoke: async () => terminal,
    },
  } as ReturnType<typeof createClient<Database>>;
}

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ["SUPABASE_PUBLISHABLE_KEY"] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(", ")}. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase] ${message}`);
    return createMissingSupabaseClient(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
